-- Executar primeiro o Create Database, após entrar no QueryTool da database desafioNeki 
-- e executar o comando dentro do "Begin".
	
CREATE DATABASE "desafioNeki"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

BEGIN;


CREATE TABLE IF NOT EXISTS public.skills
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    img_url character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT skills_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    senha character varying(255) COLLATE pg_catalog."default",
    usuario character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario_skill
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level bigint,
    skill_id bigint,
    usuario_id bigint,
    CONSTRAINT usuario_skill_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.usuario_skill
    ADD CONSTRAINT fk6v0kbm5kr0oqhryiljb7b66p2 FOREIGN KEY (skill_id)
    REFERENCES public.skills (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_skill
    ADD CONSTRAINT fkl5u0nu7syarblubr3fb55dfwm FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


INSERT INTO skills (nome, descricao, img_url) VALUES
('JavaScript', 'Programação em JavaScript', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRss-86vRuxOArrVRmMgerLZ5pi8yCs6U7zsQ&s'),
('Front-End', 'Desenvolvimento Front-End', 'https://kinsta.com/pt/wp-content/uploads/sites/3/2021/12/front-end-developer-1024x512.png'),
('UI Design', 'Design de Interfaces', 'https://miro.medium.com/v2/resize:fit:1400/0*8ecOxVcN8RETZwti.png'),
('Back-End', 'Desenvolvimento Back-End', 'https://kinsta.com/pt/wp-content/uploads/sites/3/2021/12/back-end-developer-1024x512.png'),
('SQL', 'Banco de Dados SQL', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUAbQJ1smNrIvvMazOCFGA3d2T7aqawCi19Q&s'),
('Git', 'Controle de Versão com Git', 'https://pbs.twimg.com/profile_images/1372304699601285121/5yBS6_3F_400x400.jpg'),
('DevOps', 'DevOps e CI/CD', 'https://www.targetso.com/wp-content/uploads/2024/02/DevOps-Tools.png'),
('Testes Automatizados', 'Testes Automatizados', 'https://hermes.dio.me/articles/cover/e6451774-7ba5-41e7-8c97-bd0fd50e0b86.jpg'),
('Mobile', 'Desenvolvimento Mobile', 'https://miro.medium.com/v2/resize:fit:1400/1*LQtKmVt10K_R644y12jaVg.jpeg'),
('Segurança', 'Segurança da Informação', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV99kQ3HR2wGrlVqlKz45L2ROc_xvpplRvZw&shttps://example.com/images/security.png');

END;
